spring.application.name=mobility-backend

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.briotpjealadhecdcuah
spring.datasource.password=12219461@kmdz

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.address=0.0.0.0
server.compression.enabled=false
spring.mvc.async.request-timeout=5000