spring.application.name=mobility-backend

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.briotpjealadhecdcuah
spring.datasource.password=12219461@kmdz

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081
server.address=0.0.0.0
server.compression.enabled=false
spring.mvc.async.request-timeout=5000

spring.cache.type=simple
logging.level.org.springframework.cache=DEBUG
spring.jpa.open-in-view=false
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
rce.hikari.data-source-properties.prepareThreshold=0